apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dd3xy65dr-go
  janus-idp.io/tekton: dd3xy65dr-go
  backstage.io/kubernetes-id: dd3xy65dr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dd3xy65dr-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
