apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dd3xy65dr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dd3xy65dr-go 
  name: dd3xy65dr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dd3xy65dr-go 
