apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dd3xy65dr-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:be48a4c0ba443d67cf127d575ff5d9b7541d276d@sha256:9ee6e74106f255d1615ac90bc9ad8d57f39279d438f8fc5e9687176caac9a762
          name: container-image
